version: "2"
services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: password
    image: mysql:5.7.22
    ports:
      - "33306:3306"
  puma:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bundle exec puma --config config/puma.rb --environment development
    volumes:
      - ./app:/app/app
      - ./bin:/app/bin
      - ./config:/app/config
      - ./config.ru:/app/config.ru
      - ./db:/app/db
      - ./Gemfile:/app/Gemfile
      - ./Gemfile.lock:/app/Gemfile.lock
      - ./lib:/app/lib
      - ./public:/app/public
      - ./Rakefile:/app/Rakefile
      - ./scripts:/app/scripts
      - bundle:/bundle
    ports:
      - "33000:3000"
volumes:
  bundle: